AIQ: Release v3.0x8.5 for RV1106
CLs since v3.0x8.5:

7e01f246 Merge isp3x branch into isp32
7d6ec3b6 seprate nr sharp camgroup: to single algo
63b3039c aiq: log: log level warning should be default enabled
4833f537 aiq: build script: Fix menu display in bash
113471f7 CCM: fix bug of scale adjust
858eb0ca AF: fix undefined reference to pdaf function
af49411d aiq: build: RV1106 temporarily use ISP 30 for test
88e9755e aiq: Fix build for isp21
69755391 aiq: build scripts: Support select SoC target
b1f670c4 aiq: algos: ccm: Support modular build
70d29334 aiq: algos: 3dlut: Support modular build
30029468 aiq: parser v2: Separate module by hardware version
13718e0f aiq: algos: af: Fix segfault if af disabled
9855fb6a AF: support modular build
71df54a4 nr sharp blc modify compile file
f223d616 aiq: camgroup: Fix build error after separate core config
e36198ce aiq: build: Enable modular build by target soc model
c797d6a3 aiq: core: Move hardware related to CoreConfig.h
da3c3520 aiq: build: Remove third party opencv2 code
a21ffaac aiq: algos: cac: Support modular build
29e86c1f aiq: algos: eis: Support modular build
25f5848d aiq: algos: orb: Support modular build
4b7076ae aiq: algos: gic: Support modular build
44597ee1 aiq: algos: awb v20/v21: Support modular build
2beeb4fa aiq: algos: ynr v2: Support modular build
a612e726 AF: change librkaiq_pdaf.a to gcc8.3 version
bf300357 aiq: core: alloc pdaf stat buffer when pdaf is enabled in iq
f5def49c aiq: core: Separate hardware version related configs
df0b191c aiq: build: Add configuration file rules
4665dfed aiq: build: Enable thumb mode for arch arm
6d65b07f aiq: build: Also support asan for RelWithDebInfo build
88f12c92 aiq: share item: Use SFINAE to call reset function
70dc6277 aiq: build: Add install command
27751e52 isp_demo: Fix build failure for lsc test
f56cc330 aiq: analyzer group: Reduce cache unready msgs count to 4
63f93f49 aiq: algos: dpcc: Optimize for performance
151c0ed1 aiq: calibv2: Default disable IQ_DEBUG
422015de Merge isp3x branch into isp32
8b50c2b9 Merge isp3x branch into isp32

Change-Id: If34acb5da44e0c50057864f9d199f0cb9eceaf0b
Signed-off-by: Cody Xie <cody.xie@rock-chips.com>

Former-commit-id: a23e2922b6d46fcbd640f5fc2a2d9cae464ba9c9